version: "3"
services:
  front-end:
    build:
      context: front-end
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./out:/app/out
    env_file:
      - .env

  back-end:
    build: 
      context: back-end
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
  
  mongo:
    image: mongo:6.0.5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    env_file:
      - .env
    volumes:
      - mongodb_data_container:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  
volumes:
  mongodb_data_container:
