import Head from 'next/head'
import Navbar from './navbar';
import Footer from './footer';

type Props = {
    children: React.ReactNode,
  };

export default function Layout({ children }: Props) {
    return (
        <>
            <Head>
                <title>PT App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main>
                {children}
            </main>
            <Footer />
        </>
    );
}